source 'https://cdn.cocoapods.org/'
source 'https://github.com/kingschat/KingsPay-GS-iOS'

platform :ios, '11.0'

target 'KingsPayGS-iOS-Sample' do
    use_frameworks!
    pod 'AFNetworking'
    pod 'RxSwift'
    pod 'RxRelay'
    pod 'RxCocoa'
    pod 'SPTPersistentCache'
    pod 'SwiftyRSA'
    pod 'GS', '0.1.4', :source => "git@github.com:kingschat/KingsPay-GS-iOS.git"
end
